import {
  CATEGORIES,
  getCategoryLabel,
  normalizeCategory,
} from "@/lib/categories";
import type { AIInsight, Expense, MonthlySummary } from "@/types";
import { format, parseISO } from "date-fns";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const PAGE_W = 210;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;
const TEAL: [number, number, number] = [1, 148, 154];
const TEAL_DARK: [number, number, number] = [1, 75, 78];
const MINT: [number, number, number] = [230, 245, 245];
const TEXT: [number, number, number] = [30, 41, 59];
const MUTED: [number, number, number] = [100, 116, 125];

type AutoTableDoc = jsPDF & { lastAutoTable: { finalY: number } };

/** jsPDF default fonts don't support ₹ — use Rs. for clean PDF output */
function formatPdfCurrency(amount: number): string {
  const abs = Math.abs(amount);
  const formatted = new Intl.NumberFormat("en-IN", {
    maximumFractionDigits: 0,
  }).format(abs);
  return amount < 0 ? `-Rs. ${formatted}` : `Rs. ${formatted}`;
}

/** Strip/replace characters that break Helvetica metrics in jsPDF */
function sanitizePdfText(text: string): string {
  return text
    .replace(/\u20B9/g, "Rs. ")
    .replace(/₹\s*/g, "Rs. ")
    .replace(/\bINR\s*/gi, "Rs. ")
    .replace(/[\u00A0\u2000-\u200B]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function drawLeftAlignedLines(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
): number {
  const lines = doc.splitTextToSize(sanitizePdfText(text), maxWidth);
  for (const line of lines) {
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function drawPageFooter(doc: jsPDF, page: number, total: number) {
  const y = 287;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by Ledger · ${format(new Date(), "dd MMM yyyy")}`, MARGIN, y);
  doc.text(`Page ${page} of ${total}`, PAGE_W - MARGIN, y, { align: "right" });
}

function drawHeader(
  doc: jsPDF,
  monthLabel: string,
  summary: MonthlySummary,
  previousSummary: MonthlySummary | null
): number {
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Ledger", MARGIN, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Monthly Expense Report", MARGIN, 25);

  doc.setFontSize(10);
  doc.text(monthLabel, MARGIN, 33);

  let y = 52;

  // Summary stat boxes
  const stats: { label: string; value: string }[] = [
    { label: "Total Expenditure", value: formatPdfCurrency(summary.totalSpent) },
    { label: "Transactions", value: String(summary.expenseCount) },
  ];

  if (summary.totalInvested > 0) {
    stats.push({
      label: "Investments",
      value: formatPdfCurrency(summary.totalInvested),
    });
  }

  if (previousSummary) {
    const diff = summary.totalSpent - previousSummary.totalSpent;
    const sign = diff >= 0 ? "+" : "";
    stats.push({
      label: "vs Last Month",
      value: `${sign}${formatPdfCurrency(diff)}`,
    });
  }

  const boxW = (CONTENT_W - (stats.length - 1) * 6) / stats.length;
  stats.forEach((stat, i) => {
    const x = MARGIN + i * (boxW + 6);
    doc.setFillColor(...MINT);
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, boxW, 22, 2, 2, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(stat.label, x + 5, y + 8);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...TEAL_DARK);
    doc.text(stat.value, x + 5, y + 17);
  });

  return y + 32;
}

function sectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...TEAL_DARK);
  doc.text(title, MARGIN, y);

  doc.setDrawColor(...TEAL);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y + 2, MARGIN + 36, y + 2);

  return y + 10;
}

function tableDefaults() {
  return {
    theme: "plain" as const,
    margin: { left: MARGIN, right: MARGIN },
    headStyles: {
      fillColor: TEAL,
      textColor: [255, 255, 255] as [number, number, number],
      fontStyle: "bold" as const,
      fontSize: 9,
      cellPadding: 5,
    },
    bodyStyles: {
      fontSize: 9,
      cellPadding: 4,
      textColor: TEXT,
    },
    alternateRowStyles: {
      fillColor: [248, 252, 252] as [number, number, number],
    },
    styles: {
      lineColor: [220, 235, 235] as [number, number, number],
      lineWidth: 0.2,
    },
  };
}

function drawInsights(doc: jsPDF, insights: AIInsight[], startY: number): number {
  let y = sectionTitle(doc, "AI Insights", startY);

  if (!insights.length) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text("No insights available for this month.", MARGIN, y + 4);
    return y + 12;
  }

  for (const insight of insights) {
    const textWidth = CONTENT_W - 12;
    const title = sanitizePdfText(insight.title);
    const detail = sanitizePdfText(insight.detail);
    const titleLines = doc.splitTextToSize(title, textWidth);
    const detailLines = doc.splitTextToSize(detail, textWidth);
    const blockH = 10 + titleLines.length * 5 + 3 + detailLines.length * 4.5 + 8;

    if (y + blockH > 265) {
      doc.addPage();
      y = MARGIN + 8;
    }

    doc.setFillColor(...MINT);
    doc.setDrawColor(200, 225, 225);
    doc.setLineWidth(0.3);
    doc.roundedRect(MARGIN, y, CONTENT_W, blockH, 2, 2, "FD");

    // Type badge
    const badgeColors: Record<string, [number, number, number]> = {
      warning: [214, 69, 69],
      positive: [1, 138, 94],
      neutral: TEAL,
    };
    const badge = badgeColors[insight.type] ?? TEAL;
    doc.setFillColor(...badge);
    doc.roundedRect(MARGIN + 5, y + 5, 28, 5, 1, 1, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(255, 255, 255);
    doc.text(insight.type.toUpperCase(), MARGIN + 19, y + 8.5, { align: "center" });

    let innerY = y + 14;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT);
    innerY = drawLeftAlignedLines(doc, title, MARGIN + 6, innerY, textWidth, 5);
    innerY += 3;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    drawLeftAlignedLines(doc, detail, MARGIN + 6, innerY, textWidth, 4.5);

    y += blockH + 6;
  }

  return y;
}

export function generateMonthlyPdf(input: {
  summary: MonthlySummary;
  previousSummary: MonthlySummary | null;
  insights: AIInsight[];
  topExpenses: Expense[];
}): Buffer {
  const doc = new jsPDF();
  const { summary, previousSummary, insights, topExpenses } = input;
  const monthLabel = format(parseISO(`${summary.month}-01`), "MMMM yyyy");

  let y = drawHeader(doc, monthLabel, summary, previousSummary);

  y = sectionTitle(doc, "Spending by Category", y);

  const categoryRows = summary.byCategory
    .filter((c) => c.total > 0)
    .sort((a, b) => b.total - a.total)
    .map((c) => [
      getCategoryLabel(c.category),
      CATEGORIES[normalizeCategory(c.category)].isInvestment ? "Investment" : "Spending",
      formatPdfCurrency(c.total),
      String(c.count),
    ]);

  autoTable(doc, {
    startY: y,
    head: [["Category", "Type", "Amount", "Count"]],
    body: categoryRows,
    ...tableDefaults(),
    columnStyles: {
      0: { cellWidth: 65 },
      1: { cellWidth: 35 },
      2: { cellWidth: 40, halign: "right" },
      3: { cellWidth: 24, halign: "center" },
    },
  });

  y = (doc as AutoTableDoc).lastAutoTable.finalY + 14;

  if (topExpenses.length) {
    if (y > 240) {
      doc.addPage();
      y = MARGIN + 8;
    }

    y = sectionTitle(doc, "Top Expenses", y);

    autoTable(doc, {
      startY: y,
      head: [["Description", "Category", "Amount", "Date"]],
      body: topExpenses.slice(0, 10).map((e) => [
        e.description ?? "-",
        getCategoryLabel(e.category),
        formatPdfCurrency(Number(e.amount)),
        e.expense_date,
      ]),
      ...tableDefaults(),
      columnStyles: {
        0: { cellWidth: 62 },
        1: { cellWidth: 42 },
        2: { cellWidth: 36, halign: "right" },
        3: { cellWidth: 28 },
      },
    });

    y = (doc as AutoTableDoc).lastAutoTable.finalY + 14;
  }

  if (y > 220) {
    doc.addPage();
    y = MARGIN + 8;
  }

  drawInsights(doc, insights, y);

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    drawPageFooter(doc, p, totalPages);
  }

  return Buffer.from(doc.output("arraybuffer"));
}
